spring.application.name=catalogue
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=72a9a5ed4ee48e59b0f71b87ade63d0ae72b03312c90efba8acab4c7238dba95
jwt.expiration=3600000

